version: "3.8"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        nginx['client_max_body_size'] = '0'
  runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./runner:/etc/gitlab-runner"
