concurrent = 4
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "4d160326fc4d"
  url = "http://172.21.0.3/"
  token = "2jMogczsV97GzdQdZk2S"
  executor = "docker"
  clone_url = "http://172.21.0.3/"
  [runners.docker]
    tls_verify = false
    image = "archlinux:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    # additions start here
    allowed_images = ["archlinux:*", "archlinux/archlinux:*"]
    cap_add = ["sys_admin"]
    runtime = "kata"
    network_mode = "runner-config_default"
    cpus = "3"  # 3+1 default vcpu
    memory = "0"  # 0+2048MiB default memory
